
    create table alumnos (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table cursadas (
        id bigint generated by default as identity (start with 1),
        materia_id bigint,
        alumno_id bigint,
        primary key (id)
    )

    create table materias (
        tipo varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        nombre varchar(255) not null,
        creditos integer,
        homogenea boolean,
        primary key (id)
    )

    create table notas (
        id bigint generated by default as identity (start with 1),
        comentario varchar(255),
        numero integer not null,
        cursada_id bigint,
        posicion integer,
        primary key (id)
    )

    alter table cursadas 
        add constraint FK_s99chs3qqu6qiv4btyecawddm 
        foreign key (materia_id) 
        references materias

    alter table cursadas 
        add constraint FK_mha4rlqje99n9gf0vkq9vrg5f 
        foreign key (alumno_id) 
        references alumnos

    alter table notas 
        add constraint FK_hj23pv7gylj67uap15548nbf4 
        foreign key (cursada_id) 
        references cursadas
